### ISSUE TITLE
[Design][End User] Cast  - Search Guest

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#69]
#27
`Cast→Guestを検索できる
`
ので、Cast側の検索画面はGuestとは違うと思います。ランクなどがありませんかね？
![image](https://user-images.githubusercontent.com/84315397/120741770-d8fc3f00-c51f-11eb-9ad7-e2b0ce55730b.png)
![image](https://user-images.githubusercontent.com/84315397/120741834-fe894880-c51f-11eb-8875-3fda7b6a9fb5.png)

**Comment by akitoshi** [comment]
@UyenTran95 

もし可能かどうかの相談なのですが
ゲストの方もキャストと同様に
ランキング・ゲストランク（Standardなど）を対応することができますか？

お客様とゲストで、同様のUIにした方がシンプルになると思います。

・ゲスト（お客様）にもランキングを表示（売上ではなく使用金額）
・ゲストにも、ゲストランク、を追加 （ castGrade ではなく guestGrade ）
・キャストと同じく、"Standard" / "VIP" / "LoyalVIP"
・キャストと同じく、ゲストランクを手動でダッシュボードで変更

--

I'm just asking if it's possible.
Is it possible for "Guests" to be ranked in the same way as "Cast" members?
Can we support ranking and "Guest rank" (Standard, VIP, LoyalVIP )?

I think it would be simpler to use the same UI for "Guests" and "Casts".

It would be simpler to make the UI the same for "Guests" and "Casts". 

・Guests (customers) can also display their ranking (not sales, but amount spent).
・Add a "Guest rank" for guests (guestGrade instead of castGrade).
・- "Standard" / "VIP" / "LoyalVIP" like Cast Members
・Manually change the "Guest" rank in the dashboard, just like "Cast" members.

![ScreenShot_2021-06-04_13 04 20](https://user-images.githubusercontent.com/113367/120744440-f3411780-c535-11eb-8b7c-67e9fe5b38e9.png)

**Comment by UyenTran95** [comment]
そうですね。同様のUIにした方がシンプルになりますね。
開発者と確認したところ、技術的に問題がありません。同様のUIなので、工数も増えないそうです。
しかし、
キャストのランク、（Standard/VIP/LoyalVIP）
ゲストのランク、（Standard/VIP/LoyalVIP）
をそれぞれの定義を説明して頂ければ幸いです。

**Comment by akitoshi** [comment]
@UyenTran95 

ありがとうございます。良かったです。

**キャストランク（Standard/VIP/LoyalVIP）**
・それぞれ管理画面でのみ手動で変更可能
・キャストは自分で変更できない
・顧客の注文時に、ランク指定があった場合に、注文リクエストが来る
・Private Orderで設定できる料金の上限が変わる
↓
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1951431203&range=D3


**ゲストランク（Standard/VIP/LoyalVIP）**
・それぞれ管理画面でのみ手動で変更可能
・ゲストは自分で変更できない

**Comment by UyenTran95** [comment]
Chốt:

Về cơ bản giao diện màn search của Cast => Guest và ngược lại Guest => Cast sẽ giống nhau. 
Guest search Cast:
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=1%3A2047

Cast Search Guest:
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=729%3A3

Điểm khác nhau:
- các label Cast >< Guest
- Màn search: bỏ cục search theo giá ở phía CAST (Vì guest ko có giá)
- Màn search > Search bằng tag: thay màn tag tương ứng của CAST/GUEST

*Về rank của Cast và Guest. Sẽ có 3 bậc rank là: （Standard/VIP/LoyalVIP）
- 3 bậc này đều được setting tay trên màn dashboard. chỉ admin mới setting được thôi. 
- User ko thể tự đổi
- Mặc định ban đầu là Standard
